In [1]:
pip install streamlit scikit-learn seaborn joblib matplotlib

Requirement already satisfied: streamlit in c:\users\harry\anaconda3\lib\site-packages (1.32.0)
Requirement already satisfied: scikit-learn in c:\users\harry\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: seaborn in c:\users\harry\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: joblib in c:\users\harry\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: matplotlib in c:\users\harry\anaconda3\lib\site-packages (3.8.4)
Requirement already satisfied: altair<6,>=4.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (5.0.1)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (1.6.2)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (5.3.3)
Requirement already satisfied: click<9,>=7.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (8.1.7)
Collecting numpy<2,>=1.19.3 (from streamlit)
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: packaging<24,>=16.8 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (23.2)
Requirement already satisfied: pandas<3,>=1.3.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<11,>=7.1.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (10.3.0)
Collecting protobuf<5,>=3.20 (from streamlit)
  Downloading protobuf-4.25.8-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Requirement already satisfied: pyarrow>=7.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (14.0.2)
Requirement already satisfied: requests<3,>=2.27 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (13.3.5)
Requirement already satisfied: tenacity<9,>=8.1.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (8.2.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (3.1.37)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (0.8.0)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (6.4.1)
Requirement already satisfied: watchdog>=2.1.5 in c:\users\harry\anaconda3\lib\site-packages (from streamlit) (4.0.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\harry\anaconda3\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\harry\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\harry\anaconda3\lib\site-packages (from matplotlib) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\harry\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\harry\anaconda3\lib\site-packages (from matplotlib) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\harry\anaconda3\lib\site-packages (from matplotlib) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\harry\anaconda3\lib\site-packages (from matplotlib) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\harry\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: jinja2 in c:\users\harry\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.4)
Requirement already satisfied: jsonschema>=3.0 in c:\users\harry\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (4.19.2)
Requirement already satisfied: toolz in c:\users\harry\anaconda3\lib\site-packages (from altair<6,>=4.0->streamlit) (0.12.0)
Requirement already satisfied: colorama in c:\users\harry\anaconda3\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\harry\anaconda3\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.7)
Requirement already satisfied: pytz>=2020.1 in c:\users\harry\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\harry\anaconda3\lib\site-packages (from pandas<3,>=1.3.0->streamlit) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\harry\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\harry\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\harry\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\harry\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\harry\anaconda3\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in c:\users\harry\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\harry\anaconda3\lib\site-packages (from rich<14,>=10.14.0->streamlit) (2.15.1)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\harry\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\harry\anaconda3\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\harry\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\harry\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\harry\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\harry\anaconda3\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.10.6)
Requirement already satisfied: mdurl~=0.1 in c:\users\harry\anaconda3\lib\site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.0)
Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl (15.5 MB)
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   - -------------------------------------- 0.4/15.5 MB 8.5 MB/s eta 0:00:02
   - -------------------------------------- 0.7/15.5 MB 8.9 MB/s eta 0:00:02
   --- ------------------------------------ 1.4/15.5 MB 9.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.9/15.5 MB 10.7 MB/s eta 0:00:02
   ------ --------------------------------- 2.5/15.5 MB 10.7 MB/s eta 0:00:02
   ------- -------------------------------- 3.1/15.5 MB 10.8 MB/s eta 0:00:02
   --------- ------------------------------ 3.6/15.5 MB 10.8 MB/s eta 0:00:02
   ---------- ----------------------------- 4.1/15.5 MB 10.8 MB/s eta 0:00:02
   ----------- ---------------------------- 4.6/15.5 MB 10.9 MB/s eta 0:00:01
   ------------- -------------------------- 5.2/15.5 MB 11.0 MB/s eta 0:00:01
   -------------- ------------------------- 5.7/15.5 MB 11.1 MB/s eta 0:00:01
   ---------------- ----------------------- 6.2/15.5 MB 11.1 MB/s eta 0:00:01
   ----------------- ---------------------- 6.8/15.5 MB 11.1 MB/s eta 0:00:01
   ------------------ --------------------- 7.3/15.5 MB 11.1 MB/s eta 0:00:01
   -------------------- ------------------- 7.9/15.5 MB 11.2 MB/s eta 0:00:01
   --------------------- ------------------ 8.4/15.5 MB 11.2 MB/s eta 0:00:01
   ---------------------- ----------------- 8.9/15.5 MB 11.1 MB/s eta 0:00:01
   ------------------------ --------------- 9.4/15.5 MB 11.1 MB/s eta 0:00:01
   ------------------------- -------------- 9.9/15.5 MB 11.1 MB/s eta 0:00:01
   --------------------------- ------------ 10.5/15.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------- ----------- 11.0/15.5 MB 11.7 MB/s eta 0:00:01
   ----------------------------- ---------- 11.6/15.5 MB 11.5 MB/s eta 0:00:01
   ------------------------------- -------- 12.1/15.5 MB 11.9 MB/s eta 0:00:01
   -------------------------------- ------- 12.6/15.5 MB 11.3 MB/s eta 0:00:01
   --------------------------------- ------ 13.1/15.5 MB 11.3 MB/s eta 0:00:01
   ----------------------------------- ---- 13.6/15.5 MB 11.3 MB/s eta 0:00:01
   ------------------------------------ --- 14.2/15.5 MB 11.3 MB/s eta 0:00:01
   ------------------------------------- -- 14.7/15.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  15.2/15.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------  15.5/15.5 MB 11.3 MB/s eta 0:00:01
   ---------------------------------------- 15.5/15.5 MB 10.7 MB/s eta 0:00:00
Downloading protobuf-4.25.8-cp310-abi3-win_amd64.whl (413 kB)
   ---------------------------------------- 0.0/413.7 kB ? eta -:--:--
   ---------------------------------------- 413.7/413.7 kB 8.8 MB/s eta 0:00:00
Installing collected packages: protobuf, numpy
  Attempting uninstall: protobuf
    Found existing installation: protobuf 6.31.1
    Uninstalling protobuf-6.31.1:
      Successfully uninstalled protobuf-6.31.1
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.6
    Uninstalling numpy-2.2.6:
      Successfully uninstalled numpy-2.2.6
Successfully installed numpy-1.26.4 protobuf-4.25.8
Note: you may need to restart the kernel to use updated packages.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
opentelemetry-proto 1.38.0 requires protobuf<7.0,>=5.0, but you have protobuf 4.25.8 which is incompatible.
shap 0.50.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.

In [2]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix
import joblib
import numpy as np
import matplotlib.pyplot as plt
import os 
import json 

df = sns.load_dataset('titanic')

In [3]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
features = ["pclass","sex","age","sibsp","parch","fare","embarked"]
df = df[features+["survived"]]

   pclass     sex   age  sibsp  parch     fare embarked  survived
0       3    male  22.0      1      0   7.2500        S         0
1       1  female  38.0      1      0  71.2833        C         1
2       3  female  26.0      0      0   7.9250        S         1
3       1  female  35.0      1      0  53.1000        S         1
4       3    male  35.0      0      0   8.0500        S         0

In [ ]:
df.isna().sum()

pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
survived      0
dtype: int64

In [12]:
df["age"]= df["age"].fillna(df["age"].median())
df["embarked"] = df["embarked"].fillna("S")

In [11]:
df["embarked"].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [13]:
df.isna().sum()

pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
survived    0
dtype: int64

In [14]:
X= df[features]
y = df["survived"]

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=23, stratify=y)

In [16]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False),["sex","embarked"]),
        ("num","passthrough",["pclass","age","sibsp","parch","fare"])
    ]
)

In [17]:
pipeline = Pipeline([
    ("preprocessor",preprocessor),
    ("classifier",RandomForestClassifier(n_estimators=100,random_state=23))
])

In [18]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  ['sex', 'embarked']),
                                                 ('num', 'passthrough',
                                                  ['pclass', 'age', 'sibsp',
                                                   'parch', 'fare'])])),
                ('classifier', RandomForestClassifier(random_state=23))])

In [26]:
y_pred = pipeline.predict(X_test)
y_proba =pipeline.predict_proba(X_test)[:,1]
report = classification_report(y_test,y_pred, output_dict=True)
auc = float(roc_auc_score(y_test,y_proba))
cm = confusion_matrix(y_test,y_pred).tolist()

In [28]:
os.makedirs("artifacts",exist_ok=True)
joblib.dump(pipeline,"artifacts/titanic_model.pkl")

['artifacts/titanic_model.pkl']

In [29]:
with open("artifacts/metric.json","w") as f:
    json.dump({"classification_report":report, "roc_auc_score":auc, "confusion_matrix":cm},f, indent=2)

In [32]:
fig, ax = plt.subplots(figsize=(4,4))
ax.matshow(confusion_matrix(y_test,y_pred), cmap="Blues", alpha=0.7)
for (i,j), z in np.ndenumerate(confusion_matrix(y_test,y_pred)):
    ax.text(j, i, str(z), ha="center",va="center")
ax.set_xlabel("Predicted")
ax.set_ylabel("Actual")
plt.title(f"Confusion matrix (AUC={auc:.3f})")
plt.savefig("artifacts/confusion_matrix.png",bbox_inches="tight")
plt.close()